services:
  telegram-forward-bot:
    build: .
    env_file:
      - .env
    environment:
      # Store database inside the mounted data volume
      DB_PATH: /app/data/bot.db
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    restart: unless-stopped
